server:
  port: 8080

logging:
  level:
    com.example.kafka.consumer: debug

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: group-id-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted.packages: "*"
            type.mapping: "testMessage:com.example.kafka.consumer.domain.dto.TestMessage"

  output:
    ansi:
      enabled: ALWAYS

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true